#!/bin/bash

## Created By Aditya Shakya

rofi -modi drun -show drun -location 1 -xoffset 10 -theme orange-applauncher -show-icons -theme-str 'window { width: 20%; }' -theme-str 'listview { columns: 1; }' -theme-str 'window { font: "Gohu GohuFont 8"; }' -icon-theme "Flat-Remix-Yellow-Dark"
