#!/bin/bash

## Created By Aditya Shakya

rofi -modi drun -show drun -location 1 -xoffset 10 -yoffset 32 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -show-icons -icon-theme "Flat-Remix-Yellow-Dark" -theme orange -font "Gohufont 8"
