#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -lines 6 -theme orange-applauncher -theme-str 'window { width: 12%; }' -theme-str 'window { font: "Gohu GohuFont 8"; }' <<< "	Lock|	Logout|	Suspend|	Hibernate|	Reboot|	Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) i3-nagbar -t warning "You are being logged out"; i3-msg exit ;;
		*Suspend) systemctl suspend ;;
		*Hibernate) systemctl hibernate ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
