#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -10 -lines 6 -theme orange-applauncher -theme-str 'window { width: 12%; }' -theme-str 'window { font: "Gohu GohuFont 8"; }' <<< " Lock| Logout| Suspend| Hibernate| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) cinnamon-screensaver-command -l ;;
                *Logout) cinnamon-screensaver-command -l -m "Logging you out..."; i3-msg exit ;;
		*Suspend) cinnamon-screensaver-command -l -m "Putting system to sleep..."; systemctl suspend ;;
		*Hibernate) cinnamon-screensaver-command -l -m "Putting system to deep sleep..."; systemctl hibernate ;;
                *Reboot) cinnamon-screensaver-command -l -m "Rebooting..."; systemctl reboot ;;
                *Shutdown) cinnamon-screensaver-command -l -m "Shutting down..."; systemctl -i poweroff
            esac
