#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 6 -font "Gohu GohuFont 8" -theme orange <<< "	Lock|	Logout|	Suspend|	Hibernate|	Reboot|	Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) i3-nagbar -t warning "You are being logged out"; i3-msg exit ;;
		*Suspend) systemctl suspend ;;
		*Hibernate) systemctl hibernate ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
