#!/bin/sh
while read file
do
	case "$1" in
	"C-d")
		mv "$file" ~/.local/share/Trash/files/ ;;
	"C-r")
		convert -rotate 90 "$file" "$file" ;;
	"C-c")
		convert -format png "$file" - | xclip -selection clipboard -target image/png ;;
	esac
done
